### ISSUE TITLE
v0.1.0-alpha Roadmap

### ISSUE THREAD

**Issue by zilladotexe** [larabb/larabb#1]
## Overview
This is a roadmap for the alpha release of LaraBB. Items will be added/removed/changed frequently as development continues.

### General
- [ ] Set up basic admin interface
- [ ] Create forum module, allowing posting/editing/replying/deleting
- [ ] Users creation expansion
- [ ] Users profile
- [ ] Users roles such as admin, moderator, regular user
- [ ] Split forum into categories and boards

### Core
- [ ] Make sure all language strings are translatable.
- [ ] Allow all core functions to be extensible
